name: App run check

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "app/**"

jobs:
  app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            app

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: app
        run: npm ci

      - name: Run checks
        working-directory: app
        run: npm run check
