name: App run check

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "github-oauth/**"

jobs:
  github-oauth:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            github-oauth

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: github-oauth
        run: npm ci

      - name: Run checks
        working-directory: github-oauth
        run: npm run check
