version: "3.8"

services:
  cms-oauth:
    image: ghcr.io/rickli-cloud/cms-oauth
    container_name: cms-oauth
    environment:
      OAUTH_CLIENT_ID:
      OAUTH_CLIENT_SECRET:
      # PORT:
      # LOG_LEVEL:
      # LOG_PATH:
      # ERR_LOG_LEVEL:
      # ACCESS_LOG_LEVEL:
    volumes:
      - $PWD/logs:/home/logs
    ports:
      - 8000:8000
